[package]
name = "yacme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yacme-service.workspace = true
yacme-schema.workspace = true
yacme-protocol.workspace = true
yacme-key.workspace = true
