[workspace]
members = ["yacme", "yacme-*"]

[workspace.dependencies]
arc-swap = "1.6.0"
base64ct = { version = "^1.5.3", features = ["alloc"] }
chrono = { version = "0.4.23", features = ["serde"] }
eyre = "0.6.8"
http = "0.2.9"
rand = { version = "0.8.5", features = ["getrandom"] }
reqwest = { version = "^0.11", features = [
    "rustls-tls",
    "json",
], default-features = false }
serde = { version = "^1.0.152", features = ["derive"] }
serde_json = "^1.0.93"
signature = "^2.0.0"
thiserror = "^1.0.38"
tracing = { version = "0.1.37", features = ["async-await"] }
url = { version = "2.3.1", features = ["serde"] }
der = { version = "0.6.1", features = ["std", "pem", "oid", "derive"] }
elliptic-curve = { version = "^0.12.3", features = [
    "pkcs8",
    "jwk",
    "arithmetic",
    "sec1",
] }
ecdsa = { version = "^0.15.0", features = ["std", "pkcs8", "pem"] }
rsa = "^0.8.1"
p256 = { version = "^0.12.0", features = ["pkcs8", "arithmetic", "jwk"] }
pkcs8 = { version = "^0.9.0", features = ["alloc"] }
hmac = "^0.12.1"
sha2 = "^0.10.6"
pem-rfc7468 = { version = "^0.6.0", features = ["std"] }
tokio = { version = "^1.25", features = ["full"] }
tracing-subscriber.version = "^0.3"
x509-cert = { version = "0.1.1", features = ["alloc", "pem", "std"] }
digest = { version = "^0.10.6" }
ouroboros = { version = "^0.15.6" }
mime = "0.3.16"


yacme-test = { path = "yacme-test/" }
yacme-service = { path = "yacme-service/", version = "1.0.1" }
yacme-key = { path = "yacme-key/", version = "1.0.1" }
yacme-protocol = { path = "yacme-protocol/", version = "1.0.1" }
yacme-schema = { path = "yacme-schema/", version = "1.0.1" }
yacme = { path = "yacme/" }
