[workspace]
members = ["yacme-protocol"]

[workspace.dependencies]
base64-url = "1.4.13"
chrono = { version = "0.4.23", features = ["serde"] }
eyre = "0.6.8"
http = "0.2.8"
reqwest = { version = "^0.11", features = [
    "rustls-tls",
    "json",
], default_features = false }
ring = "0.16.20"
serde = { version = "^1.0.152", features = ["derive"] }
serde_json = "^1.0.91"
thiserror = "^1.0.38"
tracing = { version = "0.1.37", features = ["async-await"] }
url = { version = "2.3.1", features = ["serde"] }
x509-certificate = "0.18.0"
