[package]
name = "yacme"
version = "1.1.0"
edition = "2021"
authors = ["Alex Rudy <opensource@alexrudy.net>"]
license = "MIT"
repository = "https://github.com/alexrudy/yacme"
description = "Yet another ACME client."
categories = ["asynchronous", "network-programming", "cryptography"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.6.0"
base64ct = { version = "^1.6.0", features = ["alloc"] }
chrono = { version = "0.4.24", features = ["serde"] }
eyre = "0.6.8"
http = "0.2.9"
rand = { version = "0.8.5", features = ["getrandom"] }
reqwest = { version = "^0.11", features = [
    "rustls-tls",
    "json",
], default-features = false }
serde = { version = "^1.0.158", features = ["derive"] }
serde_json = "^1.0.94"
signature = "^2.0.0"
thiserror = "^1.0.40"
tracing = { version = "0.1.37", features = ["async-await"] }
url = { version = "2.3.1", features = ["serde"] }
der = { version = "0.6.1", features = ["std", "pem", "oid", "derive"] }
elliptic-curve = { version = "^0.12.3", features = [
    "pkcs8",
    "jwk",
    "arithmetic",
    "sec1",
] }
ecdsa = { version = "^0.15.1", features = ["std", "pkcs8", "pem"] }
rsa = "^0.8.2"
p256 = { version = "^0.12.0", features = ["pkcs8", "arithmetic", "jwk"] }
pkcs8 = { version = "^0.9.0", features = ["alloc", "pem"] }
hmac = "^0.12.1"
sha2 = "^0.10.6"
pem-rfc7468 = { version = "^0.6.0", features = ["std"] }
tokio = { version = "^1.26", features = ["full"] }
tracing-subscriber.version = "^0.3"
x509-cert = { version = "0.1.1", features = ["alloc", "pem", "std"] }
digest = { version = "^0.10.6" }
ouroboros = { version = "^0.15.6" }
mime = "0.3.17"
const-oid = { version = "0.9.2", features = ["db"] }
lazy_static = { version = "1.4.0", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
lazy_static = "1.4.0"

[[example]]
name = "pebble"
path = "examples/letsencrypt-pebble.rs"
required-features = ["pebble"]

[[example]]
name = "pebble-schema"
path = "examples/low-level/pebble-schema.rs"
required-features = ["pebble"]

[[example]]
name = "show-request"
path = "examples/low-level/show-request.rs"
required-features = ["pebble"]

[features]
pebble = ["lazy_static"]
trace-requests = []

[[test]]
name = "pebble-integration"
path = "tests/pebble.rs"
required-features = ["pebble"]
