name: Release a crate
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  info:
    if: github.event.pull_request.merged
    outputs:
      is-release: ${{ steps.meta.outputs.is-release }}
      crate: ${{ steps.meta.outputs.crate-names }}
      version: ${{ steps.meta.outputs.version-actual }}
      notes: ${{ steps.meta.outputs.notes }}

    runs-on: ubuntu-latest
    steps:
      - id: meta
        uses: cargo-bins/release-meta@v1
        with:
          event-data: ${{ toJSON(github.event) }}

  release:
    needs: info
    if: needs.info.outputs.is-release == 'true'

    name: Publish Crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Publish to crates.io
        run: |
          cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
